### ISSUE TITLE
A los Coordinadores

### ISSUE THREAD

**Issue by norman-ipn** [norman-ipn/Ajedrez2018#1]
Buenos dias Coordinadores del 1CV1,

Su primera tarea es crear una página en el **Wiki** de este repositorio. 
Tendrá el número de Coordinador y su nombre.

Comenten con sus compañeros de clase que, si alguien desea trabajar con alguno de ustedes, tiene que registrarse en la página que ustedes acaban de crear. De esa forma tendrán sus equipos de trabajo.

Los coordinadores del 1 al 5 son del grupo 1CV2, por lo tanto su número de coordinador es: 

6. KevinFrias
7. AxelGarciaTello
8. DavidMadrigalB
9. YosafatM
10. renepayan
11. JakelineSalgado
12. Sergio884

**Comment by AresLOLXD** [comment]
Todos los coordinadores del 1CV1 han creado su pagina en la Wiki y todos en el grupo ya se encuentran en un grupo de trabajo.
