### ISSUE TITLE
Función “Verificar movimiento válido de cada pieza”

### ISSUE THREAD

**Issue by AxelGarciaTello** [norman-ipn/Ajedrez2018#11]
@JakelineSalgado Necesito que me digas cual va a ser el verdadero nombre de la función y que argumentos requiere para usarla.
Te recomiendo que devuelva un valor numero con los siguientes significados:
[1] : No se puede hacer el movimiento
[2]: Si se puede hacer el movimiento
[3]: Se puede comer una pieza durante el movimeinto

**Comment by JakelineSalgado** [comment]
Listo
