### ISSUE TITLE
Funcion "moverAlfil"

### ISSUE THREAD

**Issue by AxelGarciaTello** [norman-ipn/Ajedrez2018#13]
Subi un poco de pseudocodigo del movimiento del alfil. Chequenlo para verificar si si cumpe con sus necesidades o como acoplarlo mejor. Principalmente para las funciones que dependan de esta.
Las demas funciones seran parecidas, favor de tomarlo en cuenta.
@KevinFrias @DavidMadrigalB @renepayan @JakelineSalgado @YosafatM @Sergio884

**Comment by AresLOLXD** [comment]
Como ya nadie ha comentado algo, procedere a cerrar el issue
