### ISSUE TITLE
Pregunta respecto al tiempo al grupo 1CV2

### ISSUE THREAD

**Issue by AresLOLXD** [norman-ipn/Ajedrez2018#15]
Nuestro equipo de trabajo propone que la función de guardar tiempo sea que llamen a la función con un tiempo y una variable por referencia para almacenar el tiempo que están pasando.
Queremos preguntar si necesitan algo más en la función.

**Comment by JorgeIba** [comment]
Una disculpa pero ¿crees que puedas ser un poco mas detallista? la verdad no entendí muy bien lo que quieres decir.

**Comment by renepayan** [comment]
Es decir que en la función de guardar tiempo de tipo vacia, tenemos previsto sólo recibir el tiempo a guardar como un entero y el lugar a guardarlo como un apuntador a entero, creen que lo anterior cumple con el objetivo planteado en el documento?

**Comment by JorgeIba** [comment]
Lo que pedimos es que al momento en que la primera pieza sea movida, exista un tiempo que vaya retrociendo hasta 0, pero que únicamente retroceda cuando es el turno del jugador; tal tiempo debería ir mostrada en la pantalla segundo a segundo. No sé si eso aclare tu duda.

**Comment by AresLOLXD** [comment]
Podemos hacer las funciones para que su grupo decida cuando llamar las funciones pero no vamos a encargarnos de hacerlas llamar, ya que eso no nos corresponde

**Comment by AresLOLXD** [comment]
Si no hay ningun otro comentario procederé a cerrar el issue, están de acuerdo los coordinadores del 1CV2?

**Comment by AresLOLXD** [comment]
Bueno, no puedo seguir esperando una respuesta ya que mi equipo procederá a realizar la Wiki, asi que cierro el issue
