### ISSUE TITLE
Falta información en la Wiki

### ISSUE THREAD

**Issue by norman-ipn** [norman-ipn/Ajedrez2018#16]
Falta agregar información sobre el módulo con el que van a trabajar
y las funciones que identificaron.
Cierra este issue cuando tengas la wiki completa.

**Comment by JorgeIba** [comment]
¿A qué se refiere con módulo?

**Comment by norman-ipn** [comment]
La parte del documento con la que va a trabajar cada equipo, revisen las páginas de otros coordinadores, algunos tienen bastante trabajo avanzado, otras wikis se ven muy "pobres".
