### ISSUE TITLE
Error en el documento 2 (Algoritmia Ajedrez)

### ISSUE THREAD

**Issue by renepayan** [norman-ipn/Ajedrez2018#2]
Durante la fase de planeacion se determino que el ajedrez no seria competitivo, pero en el documento se encuentra una sección destinada al tiempo por jugador

[
![sadassa](https://user-images.githubusercontent.com/4644454/46831631-89aee200-cd69-11e8-8145-9ac192a5b176.png)
](url)

**Comment by DonaldoAyala** [comment]
Tenemos que preguntar eso bien con el profe, porque al otro grupo nos comento que tenía que llevar un tiempo limitado por jugador

**Comment by norman-ipn** [comment]
Los documentos generados por cada grupos se tomarán como base para el desarrollo y ya no pueden cambiar. Las fases de planeación de cada grupo fueron diferentes pero no están mal, ninguna de las dos.
