### ISSUE TITLE
Observaciones Algoritmo del peón

### ISSUE THREAD

**Issue by AxelGarciaTello** [norman-ipn/Ajedrez2018#3]
El peón no tiene movimientos especiales (captura al paso).

**Comment by AresLOLXD** [comment]
El error es poco descriptivo y no asignaste a los coordinadores, asi como olvidaste agregar una captura de pantalla

**Comment by norman-ipn** [comment]
@AxelGarciaTello  Revisa el _issue_ respeto al Rey y el Jaque, si hay algo que comentar sobre el movimiento del peón usa esen estilo. Cierren este _issue_ cuando concluyan el tema.
