### ISSUE TITLE
Agregar compañero

### ISSUE THREAD

**Issue by AxelGarciaTello** [norman-ipn/Ajedrez2018#32]
@norman-ipn 
Buenos tardes profesor. Queremos comentarle que no ha agregado a nuestro compañero Alan en el repositorio.
Su nombre de usuario es AlanPidal y su correo es alanpidal@gmail.com

**Comment by norman-ipn** [comment]
Ya le mandé invitación, pero no la ha aceptado

**Comment by AxelGarciaTello** [comment]
Esta bien, le comento a Alan.
Gracias
