### ISSUE TITLE
Duda para el grupo 1CV1 acerca del documento.

### ISSUE THREAD

**Issue by JorgeIba** [norman-ipn/Ajedrez2018#33]
En el punto 11.7 viene un apartado llamado "Establecer los límites del tablero" y mi equipo de trabajo no tiene muy en claro a qué se refieren.

**Comment by JakelineSalgado** [comment]
Es establecer el número de columnas y filas que hay en el tablero

**Comment by KevinFrias** [comment]
En que no se puedan mover más casillas de las que existe en el tablero
