### ISSUE TITLE
Jaque

### ISSUE THREAD

**Issue by Sergio884** [norman-ipn/Ajedrez2018#38]
@AxelGarciaTello  ¿Que es lo que harán o como trataran el Jaque exactamente?
Si abordaran los casos para impedir el Jaque.
Ya que el jaque, como jugada de amenaza de captura que es, solo se puede evadir de una las tres siguientes maneras:
*Interponiendo una pieza entre la pieza agresora y la pieza agredida (esto no es posible contra los ataques del caballo o del peón).
*Capturando la pieza agresora.
*Moviendo la pieza agredida (el rey) a un escaque fuera de la acción de las piezas contrarias.

**Comment by AresLOLXD** [comment]
Y como esperas que los demas modulos sepan que hubo un jaque si no devuelve ningun valor?

**Comment by AxelGarciaTello** [comment]
Con base a los que hablamos ayer, la función devolvera los siguentes valores:
0: si no esta en jaque
1: si el rey blanco esta en jaque
2: si el rey negro esta en jaque
