### ISSUE TITLE
Error en el documento del 1CV2(Algoritmia Ajedrez)

### ISSUE THREAD

**Issue by AresLOLXD** [norman-ipn/Ajedrez2018#4]
Encontramos un error en el documento, ya que el Rey nunca puede hacer jaque, es una regla y si pasara eso, serian tablas
![reporte](https://user-images.githubusercontent.com/7190526/46834103-1a88bc00-cd70-11e8-9bf8-314d991c2f68.png)

**Comment by DonaldoAyala** [comment]
Gracias por comentarlo, si, acabo de buscarlo y es ilegal, aunque supongo que si están los reyes cerca, habría una restricción de movimiento de alguno de los dos reyes, por ejemplo si hay una casilla de por medio entre reyes, no se podría mover hacia esa casilla.

**Comment by DonaldoAyala** [comment]
http://www.chess-poster.com/spanish/correo/correo_2005/puede_un_rey_hacer_mate_a_otro_rey.htm

**Comment by norman-ipn** [comment]
Cerrado, esta función deberá estar vacía. Sólo se programará para tener completo el documento, pero se incluirá en los comentarios la razón por la cual no es posible realizar la función.
