### ISSUE TITLE
Redundancia en movimientos (Torre y Rey)

### ISSUE THREAD

**Issue by AxelGarciaTello** [norman-ipn/Ajedrez2018#5]
El movimiento del "enroque" esta considerado en las funciones "movimientosEspecialesRey" & "movimientosEspecialesTorre".
@paul-cruz

**Comment by AresLOLXD** [comment]
@norman-ipn

**Comment by paul-cruz** [comment]
Así es @AxelGarciaTello, el movimiento de enroque  fue lo que consideramos en movimientosEspecialesRey y movimientosEspecialesTorre.

**Comment by paul-cruz** [comment]
Okey profe, entendido.
