### ISSUE TITLE
¿Comó hacer jaque con el Rey?

### ISSUE THREAD

**Issue by AxelGarciaTello** [norman-ipn/Ajedrez2018#6]
En reglas del ajedrez, los reyes no pueden aproximarse entre sí a una casilla, si bien, es posible que el Rey pueda bloquear medios de escape del Rey contrario, no puede crear un jaque por sí mismo.

**Comment by AresLOLXD** [comment]
Duplicaste mi issue, ya cree uno acerca de esto
