### ISSUE TITLE
Restricción: Verficar Movimiento de cada casilla

### ISSUE THREAD

**Issue by Ruben35** [norman-ipn/Ajedrez2018#7]
Nosotros creemos que la restricción "Verificar movimiento válido de cada pieza" es muy general y debe acomodarse a cada pieza, por lo que proponemos que cada quien haga su verificar

@AxelGarciaTello @DavidMadrigalB @JakelineSalgado

**Comment by JakelineSalgado** [comment]
Tienes razón, verificar movimientos validos entra en las funciones de cada pieza.

**Comment by Ruben35** [comment]
entonces se desarrollará una función validar movimiento para cada pieza (por ende cada quién hace su función) o se hará la general (los que hagan restricciones)?
